# Generated by Django 4.2.6 on 2023-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_directoryitem_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileitem',
            name='storageitem_ptr',
        ),
        migrations.RemoveField(
            model_name='storageitem',
            name='last_access',
        ),
        migrations.RemoveField(
            model_name='storageitem',
            name='name',
        ),
        migrations.AddField(
            model_name='storageitem',
            name='is_dir',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DirectoryItem',
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
    ]
