# Generated by Django 4.2.6 on 2023-11-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0003_remove_fileitem_storageitem_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootStorageItem',
            fields=[
                ('storageitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='storage.storageitem')),
                ('user_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('storage.storageitem',),
        ),
    ]
