# Generated by Django 4.2.6 on 2023-11-19 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage', '0004_rootstorageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rootstorageitem',
            name='user_root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
