# Generated by Django 4.2.6 on 2023-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_rootstorageitem_user_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='name',
            field=models.CharField(default='empty', max_length=255),
            preserve_default=False,
        ),
    ]
