version: '3.7'
services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${SQL_DATABASE}'
      POSTGRES_USER: '${SQL_USER}'
      POSTGRES_PASSWORD: '${SQL_PASSWORD}'
    volumes:
      - '~/data/postgres:/var/lib/postgresql/data/'
    restart: always
  minio:
    image: 'minio/minio:latest'
    command: 'server --console-address ":9001" /data/'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - '~/data/minio:/data'
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://localhost:9000/minio/health/live'
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
